[[main]]
  name = "爱"
  pageRef = "docs"
  weight = 10

[[main]]
  name = "诗"
  pageRef = "posts"
  weight = 20

[[main]]
  name = "归"
  pageRef = "archive"
  weight = 30

[[main]]
  name = "情"
  weight = 40
[[main]]
  identifier = "goods"
  name = "忆"
  pageRef = "goods"
  parent = '情'
  weight = 10
[[main]]
  identifier = "comments-with-twikoo"
  name = "秘"
  url = "https://seven-demo-with-twikoo.netlify.app/"
  parent = '情'
  weight = 20